version=1.0.1
url=https://github.com/hamdiademi/fresh-carpet-releases/releases/download/v1.0.1/carpet-wash.jar
sha256=a73721100a4e9d67c9cf08c22d593966e48030aaeffb3ffb9128c402da598b6e
notes=Test release - checking the update system works
