version=1.0.2
url=https://github.com/hamdiademi/fresh-carpet-releases/releases/download/v1.0.2/carpet-wash.jar
sha256=8db6b45d12b35196e300c73990439c36d0d0cb7ac9d3f009868357e99f0f98e6
notes=Title bar follows dark mode.\nDrag locations in Admin Settings to reorder them.\nExtra backups on closing and every few hours.
